title: OrangeMike photography
author: Mikecole_10
email: OrangeMike.photography@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my personal and photography brand, OrangeMike photography.
 I want to invite ou guys to check this litte test site out. Please feel free to leave a review of some sort.

# social links
twitter_username: OrangeMikephoto
github_username:  Mikecole_10

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
